general.import = [
# Shared configuration
"~/.config/alacritty/alacritty-common.toml",

# Local configuration
# Use ~/dotfiles/alacritty/install.sh to generate file 
"~/.config/alacritty/alacritty-local.toml"]
