general {
    lock_cmd = pidof hyprlock || hyprlock                                                           # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                                                        # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on && brightnessctl -r                                  # to avoid having to press a key twice to turn on the display.
}

# Dim screen after 60 seconds idle
listener {
    timeout = 60                                                                                    # 30 seconds
    on-timeout = brightnessctl -s set 40                                                            # set monitor backlight to minimum, avoid 0 on OLED monitor
    on-resume = brightnessctl -r                                                                    # monitor backlight restore
}

# Turn off keyboard backlight after 90 seconds
listener {
    timeout = 90                                                                                    # 2.5min
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0                                          # turn off keyboard backlight
    on-resume = brightnessctl -rd rgb:kbd_backlight                                                 # turn on keyboard backlight
}

# Lock screen after 120 seconds idle
listener {
    timeout = 120                                                                                    # 2min
    on-timeout = loginctl lock-session                                                               # lock screen when timeout has passed
}

# Turn off screen after 300 seconds idle (5 minutes)
listener {
    timeout = 300                                                                                    # 5min
    on-timeout = hyprctl dispatch dpms off                                                           # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r                                         # screen on when activity is detected after timeout has fired.
}

# Suspend to RAM after 600 seconds idle (10 minutes)
listener {
    timeout = 600                                                                                   # 10min
    on-timeout = systemctl suspend                                                                  # suspend pc
}

