[General]
__userfile__=true
backlightIdleness=26
backlightIdlenessOnBatteryDischarging=true
disableIdlenessWhenFullscreen=false
enableBatteryWatcher=true
enableExtMonLidClosedActions=false
enableIdlenessBacklightWatcher=true
enableIdlenessWatcher=true
enableLidWatcher=true
hibernateKeyAction=1
iconType=0
idlenessACAction=-2
idlenessACTime=@Variant(\0\0\0\xf\0\t'\xc0)
idlenessBatteryAction=-2
idlenessBatteryTime=@Variant(\0\0\0\xf\0\t'\xc0)
idlenessTime=@Variant(\0\0\0\xf\0\x2I\xf0)
lidClosedAcAction=-1
lidClosedAction=4
lidClosedExtMonAcAction=-1
lidClosedExtMonAction=-1
monitorIdlenessACTime=@Variant(\0\0\0\xf\0\x4\x93\xe0)
monitorIdlenessBatteryTime=@Variant(\0\0\0\xf\0\x4\x93\xe0)
powerKeyAction=4
powerLowAction=4
powerLowLevel=5
powerLowWarning=30
runCheckLevel=1
showIcon=true
suspendKeyAction=4
