[General]
__userfile__=true
iconTheme=Papirus-Dark

[desktopswitch]
alignment=Left

[fancymenu]
favorites\1\desktopFile=/usr/share/applications/Alacritty.desktop
favorites\2\desktopFile=/usr/share/applications/firefox.desktop
favorites\3\desktopFile=/usr/share/applications/kvantummanager.desktop
favorites\4\desktopFile=/usr/share/applications/pcmanfm-qt.desktop
favorites\5\desktopFile=/usr/share/applications/pavucontrol-qt.desktop
favorites\size=5

[mount]
alignment=Right

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\x1\xff\xff\x1b\x1b\x17\x17\x14\x14\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\xaa\xaa\xff\xff\0\0)
hidable=false
hide-on-overlap=false
iconSize=22
lineCount=1
lockPanel=false
opacity=70
panelSize=32
plugins=fancymenu, desktopswitch, taskbar, statusnotifier, tray, mount, volume, worldclock
position=Top
reserve-space=true
screen-name=eDP-1
show-delay=0
visible-margin=true
width=100
width-percent=true

[taskbar]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=IconText
buttonWidth=220
closeOnMiddleClick=false
excludedList=
groupingEnabled=false
iconByClass=false
raiseOnCurrentDesktop=false
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=false
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=true
ungroupedNextToExisting=false
wheelDeltaThreshold=300
wheelEventsAction=0

[volume]
alignment=Right

[worldclock]
alignment=Right
autoRotate=true
customFormat="'<b>'HH:mm:ss'</b><br/><font size=\"-2\">'ddd, d MMM yyyy'<br/>'TT'</font>'"
dateFormatType=iso
dateLongNames=false
datePadDay=false
datePosition=before
dateShowDoW=false
dateShowYear=false
defaultTimeZone=America/Cancun
formatType=custom-timeonly
showDate=true
showTimezone=false
showTooltip=false
showWeekNumber=true
timeAMPM=false
timePadHour=true
timeShowSeconds=false
timeZoneWheel=true
timeZones\1\customName=
timeZones\1\timeZone=America/Cancun
timeZones\size=1
timezoneFormatType=iana
timezonePosition=below
useAdvancedManualFormat=false
