#!/bin/bash

# Set environment variables for repository
# For testing on local SSD:
# export RESTIC_REPOSITORY="/mnt/backup/home/"
# export RESTIC_PASSWORD_FILE="/etc/restic/home.repo.key"
source /etc/restic/home.repo.env

# Run the backup
echo "Starting backup at $(date)"

#echo "$RESTIC_REPOSITORY"
#echo "$RESTIC_PASSWORD_FILE"
# Optional: run this command to check the use of the password
# restic -r "$RESTIC_REPOSITORY" snapshots

# Do the backup - note "backup" comes before $HOME
#    --dry-run \
restic -r "$RESTIC_REPOSITORY" \
    --verbose \
    --tag "home" \
    backup "$HOME" \
    --exclude-file=/home/leo/scripts/backup/restic/restic-home-exclude

# Maintain backups - Keep 7 daily, 4 weekly, and 12 monthly backups
echo "Pruning old backups..."
restic -r "$RESTIC_REPOSITORY" forget \
  --keep-daily 7 \
  --keep-weekly 4 \
  --keep-monthly 12 \
  --prune \
  --tag "home"

# Check repository integrity
echo "Checking repository integrity..."
restic -r "$RESTIC_REPOSITORY" check

# Delete environment variables
unset RESTIC_PASSWORD
unset RESTIC_REPOSITORY
unset RESTIC_PASSWORD_FILE

echo "Backup completed at $(date)"
